"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.Note: This problem has been changed recently, please check that you are using the right parameters.

http://www.projecteuler.net/index.php?section=problems&id=2
"""

def problem_2():
    print "The sum of all even numbers in the Fibonacci sequence below 4,000,000 is %d" % sum(filter(is_even, fib))

def is_even(n):
    """Returns tue if n is evenly divisible by 2"""
    return (not n%2)

fib = [1, 2]

n = fib[-2] + fib[-1]
while n < 4000000:
    fib.append(n)
    n = fib[-2] + fib[-1]
